# fly.toml app configuration file generated for hireforwork-server on 2024-11-02T19:44:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hireforwork-server'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
